# -*- coding: utf-8 -*-
"""Full Game Baseball Engine Data Provider for yt2score.
Generates complete 4-inning (8 half-innings) play-by-play events, box scores, and line score.
"""

from typing import Dict, Any, List
from worker.evidence_data import get_play_evidence

def get_full_game_data() -> Dict[str, Any]:
    guest_name = "大園國小"
    home_name = "大勇國小"

    # ================== 第 1 局上半 (8 分) ==================
    top_1_events = [
        {
            "id": "pa_top1_1",
            "evidence": get_play_evidence("top1_1"),
            "order_label": "第 1 棒 (一巡)",
            "timestamp_sec": 255.0, # 04:15
            "inning_num": 1,
            "inning_half": "TOP",
            "event_type": "SINGLE",
            "result": "中前平飛安打",
            "description": f"【第 1 棒】{guest_name} 1 棒：擊出中前平飛安打順利站上一壘！隨後於 04:38 發動盜壘成功攻佔二壘 (0 出局)",
            "runs_scored": 0,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 1 棒",
            "batter_pos": "CF",
            "batter_num": "7",
            "rbi": 0,
        },
        {
            "id": "pa_top1_2",
            "evidence": get_play_evidence("top1_2"),
            "order_label": "第 2 棒 (一巡)",
            "timestamp_sec": 305.0, # 05:05
            "inning_num": 1,
            "inning_half": "TOP",
            "event_type": "HOME_RUN",
            "result": "中外野深遠場內全壘打 🔥",
            "description": f"🔥【第 2 棒】{guest_name} 2 棒：擊出中外野深遠平飛球穿越防線！一口氣繞過二三壘直奔本壘，2 分打點「場內全壘打」先馳得點！(比分 {guest_name} 2 : 0 {home_name}, 0 出局)",
            "runs_scored": 2,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 2 棒",
            "batter_pos": "SS",
            "batter_num": "6",
            "rbi": 2,
        },
        {
            "id": "pa_top1_3",
            "evidence": get_play_evidence("top1_3"),
            "order_label": "第 3 棒 (一巡)",
            "timestamp_sec": 418.0, # 06:58
            "inning_num": 1,
            "inning_half": "TOP",
            "event_type": "WALK",
            "result": "四壞球保送",
            "description": f"【第 3 棒】{guest_name} 3 棒：選到四壞球保送順利上一壘 (0 出局一壘有人)",
            "runs_scored": 0,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 3 棒",
            "batter_pos": "P",
            "batter_num": "1",
            "rbi": 0,
        },
        {
            "id": "pa_top1_4",
            "evidence": get_play_evidence("top1_4"),
            "order_label": "第 4 棒 (一巡)",
            "timestamp_sec": 472.0, # 07:52
            "inning_num": 1,
            "inning_half": "TOP",
            "event_type": "SINGLE",
            "result": "左外野平飛安打",
            "description": f"【第 4 棒】{guest_name} 4 棒：擊出左外野平飛安打！一壘跑者連跑兩個壘包進佔三壘 (0 出局一三壘有人)",
            "runs_scored": 0,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 4 棒",
            "batter_pos": "3B",
            "batter_num": "10",
            "rbi": 0,
        },
        {
            "id": "pa_top1_5",
            "evidence": get_play_evidence("top1_5"),
            "order_label": "第 5 棒 (一巡)",
            "timestamp_sec": 558.0, # 09:18
            "inning_num": 1,
            "inning_half": "TOP",
            "event_type": "SINGLE",
            "result": "右外野適時安打 (得分)",
            "description": f"【第 5 棒】{guest_name} 5 棒：擊出右外野強勁落地安打！三壘跑者輕鬆回本壘得分 (比分 {guest_name} 3 : 0 {home_name}, 0 出局一二壘有人)",
            "runs_scored": 1,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 5 棒",
            "batter_pos": "1B",
            "batter_num": "3",
            "rbi": 1,
        },
        {
            "id": "pa_top1_6",
            "evidence": get_play_evidence("top1_6"),
            "order_label": "第 6 棒 (一巡)",
            "timestamp_sec": 655.0, # 10:55
            "inning_num": 1,
            "inning_half": "TOP",
            "event_type": "WALK",
            "result": "四壞球保送 (滿壘)",
            "description": f"【第 6 棒】{guest_name} 6 棒：纏鬥選到四壞保送，{guest_name} 擠成無人出局滿壘大好得分機會！(0 出局滿壘)",
            "runs_scored": 0,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 6 棒",
            "batter_pos": "C",
            "batter_num": "2",
            "rbi": 0,
        },
        {
            "id": "pa_top1_7",
            "evidence": get_play_evidence("top1_7"),
            "order_label": "第 7 棒 (一巡)",
            "timestamp_sec": 765.0, # 12:45
            "inning_num": 1,
            "inning_half": "TOP",
            "event_type": "DOUBLE",
            "result": "右外野二壘安打 (清壘2分)",
            "description": f"🔥【第 7 棒】{guest_name} 7 棒：滿壘時敲出右外野深遠二壘安打！送回壘上 2 名跑者！(比分 {guest_name} 5 : 0 {home_name}, 0 出局二三壘有人)",
            "runs_scored": 2,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 7 棒",
            "batter_pos": "LF",
            "batter_num": "8",
            "rbi": 2,
        },
        {
            "id": "pa_top1_8",
            "evidence": get_play_evidence("top1_8"),
            "order_label": "第 8 棒 (一巡)",
            "timestamp_sec": 878.0, # 14:38
            "inning_num": 1,
            "inning_half": "TOP",
            "event_type": "STRIKEOUT",
            "result": "揮棒落空遭三振 (1出局)",
            "description": f"【第 8 棒】{guest_name} 8 棒：{home_name} 投手投出好球揮空三振！抓下本場比賽【第 1 出局】！(記分板亮 1 Out，比分 5:0)",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{guest_name} 8 棒",
            "batter_pos": "RF",
            "batter_num": "5",
            "rbi": 0,
        },
        {
            "id": "pa_top1_9",
            "evidence": get_play_evidence("top1_9"),
            "order_label": "第 9 棒 (一巡)",
            "timestamp_sec": 985.0, # 16:25
            "inning_num": 1,
            "inning_half": "TOP",
            "event_type": "SINGLE",
            "result": "中外野平飛安打",
            "description": f"【第 9 棒】{guest_name} 9 棒：擊出中外野落地安打，三壘跑者回本壘！(比分 {guest_name} 6 : 0 {home_name}, 1 出局二三壘有人)",
            "runs_scored": 1,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 9 棒",
            "batter_pos": "2B",
            "batter_num": "4",
            "rbi": 1,
        },
        {
            "id": "pa_top1_10",
            "evidence": get_play_evidence("top1_10"),
            "order_label": "第 1 棒 (二巡)",
            "timestamp_sec": 1077.0, # 17:57
            "inning_num": 1,
            "inning_half": "TOP",
            "event_type": "FIELD_OUT",
            "result": "三壘滾地刺殺 (2出局)",
            "description": f"【第 1 棒 (二巡)】{guest_name} 1 棒：擊出三壘強襲滾地球，三壘手傳一壘刺殺出局【第 2 出局】！(記分板亮 2 Out，比分 6:0)",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{guest_name} 1 棒",
            "batter_pos": "CF",
            "batter_num": "7",
            "rbi": 0,
        },
        {
            "id": "pa_top1_11",
            "evidence": get_play_evidence("top1_11"),
            "order_label": "第 2 棒 (二巡)",
            "timestamp_sec": 1170.0, # 19:30
            "inning_num": 1,
            "inning_half": "TOP",
            "event_type": "DOUBLE",
            "result": "右中外野深遠二壘打",
            "description": f"🔥【第 2 棒 (二巡)】{guest_name} 2 棒：擊出右中外野深遠二壘安打！二三壘跑者全部奔回本壘得分，進帳 2 分！(比分 {guest_name} 8 : 0 {home_name}, 2 出局二壘有人)",
            "runs_scored": 2,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 2 棒",
            "batter_pos": "SS",
            "batter_num": "6",
            "rbi": 2,
        },
        {
            "id": "pa_top1_12",
            "evidence": get_play_evidence("top1_12"),
            "order_label": "第 3 棒 (二巡)",
            "timestamp_sec": 1307.0, # 21:47
            "inning_num": 1,
            "inning_half": "TOP",
            "event_type": "INNING_SWITCH",
            "result": "內野滾地球刺殺 (3出局換局)",
            "description": f"【第 3 棒 (二巡)】{guest_name} 3 棒：擊出游擊滾地球，守備穩穩傳一壘刺殺！【第 3 出局 ‧ 攻守交換】，{guest_name} 局初猛攻 12 打席灌進 8 分完成半局！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{guest_name} 3 棒",
            "batter_pos": "P",
            "batter_num": "1",
            "rbi": 0,
        }
    ]

    # ================== 第 1 局下半 (1 分) ==================
    bottom_1_events = [
        {
            "id": "pa_bot1_1",
            "evidence": get_play_evidence("bot1_1"),
            "order_label": "第 1 棒",
            "timestamp_sec": 1416.0, # 23:36
            "inning_num": 1,
            "inning_half": "BOTTOM",
            "event_type": "GROUNDOUT",
            "result": "內野滾地刺殺 (1出局)",
            "description": f"【第 1 棒】{home_name} 1 棒：擊出二壘方向滾地球，二壘手穩穩傳一壘完成刺殺【第 1 出局】！(記分板亮 1 Out，比分 {guest_name} 8 : 0 {home_name})",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{home_name} 1 棒",
            "batter_pos": "SS",
            "batter_num": "10",
            "rbi": 0,
        },
        {
            "id": "pa_bot1_2",
            "evidence": get_play_evidence("bot1_2"),
            "order_label": "第 2 棒",
            "timestamp_sec": 1516.0, # 25:16
            "inning_num": 1,
            "inning_half": "BOTTOM",
            "event_type": "HOME_RUN",
            "result": "中外野場內全壘打 🔥",
            "description": f"🔥【第 2 棒】{home_name} 2 棒：擊出中外野深遠高飛球直擊護欄！打者快馬加鞭連繞四壘撲回本壘！1 分打點「場內全壘打」打破鴨蛋！(記分板翻牌為 {guest_name} 8 : 1 {home_name})",
            "runs_scored": 1,
            "outs_recorded": 0,
            "batter_name": f"{home_name} 2 棒",
            "batter_pos": "P",
            "batter_num": "1",
            "rbi": 1,
        },
        {
            "id": "pa_bot1_3",
            "evidence": get_play_evidence("bot1_3"),
            "order_label": "第 3 棒",
            "timestamp_sec": 1560.0, # 26:00
            "inning_num": 1,
            "inning_half": "BOTTOM",
            "event_type": "FIELD_OUT",
            "result": "三壘滾地刺殺 (2出局)",
            "description": f"【第 3 棒】{home_name} 3 棒：擊出三壘滾地球遭刺殺出局【第 2 出局】！(記分板亮 2 Out，比分 8:1)",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{home_name} 3 棒",
            "batter_pos": "3B",
            "batter_num": "6",
            "rbi": 0,
        },
        {
            "id": "pa_bot1_4",
            "evidence": get_play_evidence("bot1_4"),
            "order_label": "第 4 棒",
            "timestamp_sec": 1610.0, # 26:50
            "inning_num": 1,
            "inning_half": "BOTTOM",
            "event_type": "SINGLE",
            "result": "平飛穿越安打",
            "description": f"【第 4 棒】{home_name} 4 棒：擊出一二壘間平飛安打順利站上一壘！(2 出局一壘有人)",
            "runs_scored": 0,
            "outs_recorded": 0,
            "batter_name": f"{home_name} 4 棒",
            "batter_pos": "1B",
            "batter_num": "5",
            "rbi": 0,
        },
        {
            "id": "pa_bot1_5",
            "evidence": get_play_evidence("bot1_5"),
            "order_label": "第 5 棒",
            "timestamp_sec": 1690.0, # 28:10
            "inning_num": 1,
            "inning_half": "BOTTOM",
            "event_type": "WALK",
            "result": "四壞球保送",
            "description": f"【第 5 棒】{home_name} 5 棒：纏鬥滿球數後選到保送，一壘跑者推進二壘，攻佔得點圈！(2 出局一二壘有人)",
            "runs_scored": 0,
            "outs_recorded": 0,
            "batter_name": f"{home_name} 5 棒",
            "batter_pos": "CF",
            "batter_num": "11",
            "rbi": 0,
        },
        {
            "id": "pa_bot1_6",
            "evidence": get_play_evidence("bot1_6"),
            "order_label": "第 6 棒",
            "timestamp_sec": 2175.0, # 36:15
            "inning_num": 1,
            "inning_half": "BOTTOM",
            "event_type": "INNING_SWITCH",
            "result": "游擊飛球接殺 (3出局換局)",
            "description": f"【第 6 棒】{home_name} 6 棒：擊出游擊高飛球遭到游擊手穩穩接殺出局！【第 3 出局 ‧ 攻守交換】，完成 1 局下半！1 局結束比分 {guest_name} 8 : 1 {home_name}！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{home_name} 6 棒",
            "batter_pos": "C",
            "batter_num": "2",
            "rbi": 0,
        }
    ]

    # ================== 第 2 局上半 (0 分) ==================
    top_2_events = [
        {
            "id": "pa_top2_1",
            "order_label": "第 4 棒 (二巡)",
            "timestamp_sec": 2240.0, # 37:20
            "inning_num": 2,
            "inning_half": "TOP",
            "event_type": "SINGLE",
            "result": "平飛穿越安打",
            "description": f"【第 4 棒】{guest_name} 4 棒：2 局上首棒上場敲出穿越一壘防線平飛安打順利上壘 (0 出局一壘有人)",
            "runs_scored": 0,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 4 棒",
            "batter_pos": "3B",
            "batter_num": "10",
            "rbi": 0,
        },
        {
            "id": "pa_top2_2",
            "order_label": "第 5 棒 (二巡)",
            "timestamp_sec": 2315.0, # 38:35
            "inning_num": 2,
            "inning_half": "TOP",
            "event_type": "DOUBLE_PLAY",
            "result": "內野雙殺打 (2出局)",
            "description": f"⚡【第 5 棒】{guest_name} 5 棒：擊出游擊滾地球，{home_name} 守備發動 6-4-3 漂亮雙殺！一次抓下 2 個出局數！(2 出局無人壘)",
            "runs_scored": 0,
            "outs_recorded": 2,
            "batter_name": f"{guest_name} 5 棒",
            "batter_pos": "1B",
            "batter_num": "3",
            "rbi": 0,
        },
        {
            "id": "pa_top2_3",
            "order_label": "第 6 棒 (二巡)",
            "timestamp_sec": 2390.0, # 39:50
            "inning_num": 2,
            "inning_half": "TOP",
            "event_type": "INNING_SWITCH",
            "result": "中外野飛球接殺 (3出局換局)",
            "description": f"【第 6 棒】{guest_name} 6 棒：擊出中外野飛球遭接殺出局！【第 3 出局 ‧ 攻守交換】，{home_name} 本局展現穩健守備力保不失分！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{guest_name} 6 棒",
            "batter_pos": "C",
            "batter_num": "2",
            "rbi": 0,
        }
    ]

    # ================== 第 2 局下半 (0 分) ==================
    bottom_2_events = [
        {
            "id": "pa_bot2_1",
            "order_label": "第 7 棒",
            "timestamp_sec": 2520.0, # 42:00
            "inning_num": 2,
            "inning_half": "BOTTOM",
            "event_type": "STRIKEOUT",
            "result": "揮棒落空三振 (1出局)",
            "description": f"【第 7 棒】{home_name} 7 棒：{guest_name} 投手投出外角銳利好球揮空三振！抓下【第 1 出局】！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{home_name} 7 棒",
            "batter_pos": "LF",
            "batter_num": "8",
            "rbi": 0,
        },
        {
            "id": "pa_bot2_2",
            "order_label": "第 8 棒",
            "timestamp_sec": 2595.0, # 43:15
            "inning_num": 2,
            "inning_half": "BOTTOM",
            "event_type": "GROUNDOUT",
            "result": "二壘滾地刺殺 (2出局)",
            "description": f"【第 8 棒】{home_name} 8 棒：擊出二壘滾地球，傳一壘刺殺出局【第 2 出局】！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{home_name} 8 棒",
            "batter_pos": "RF",
            "batter_num": "7",
            "rbi": 0,
        },
        {
            "id": "pa_bot2_3",
            "order_label": "第 9 棒",
            "timestamp_sec": 2680.0, # 44:40
            "inning_num": 2,
            "inning_half": "BOTTOM",
            "event_type": "INNING_SWITCH",
            "result": "站著不動三振 (3出局換局)",
            "description": f"【第 9 棒】{home_name} 9 棒：主審拉弓！好球進壘站著不動遭三振！【第 3 出局 ‧ 攻守交換】，{guest_name} 投手演出乾淨俐落的三上三下！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{home_name} 9 棒",
            "batter_pos": "2B",
            "batter_num": "4",
            "rbi": 0,
        }
    ]

    # ================== 第 3 局上半 (2 分) ==================
    top_3_events = [
        {
            "id": "pa_top3_1",
            "order_label": "第 7 棒 (二巡)",
            "timestamp_sec": 2810.0, # 46:50
            "inning_num": 3,
            "inning_half": "TOP",
            "event_type": "SINGLE",
            "result": "左外野滾地安打",
            "description": f"【第 7 棒】{guest_name} 7 棒：敲出左邊方向穿越滾地安打上壘 (0 出局一壘有人)",
            "runs_scored": 0,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 7 棒",
            "batter_pos": "LF",
            "batter_num": "8",
            "rbi": 0,
        },
        {
            "id": "pa_top3_2",
            "order_label": "第 8 棒 (二巡)",
            "timestamp_sec": 2890.0, # 48:10
            "inning_num": 3,
            "inning_half": "TOP",
            "event_type": "SACRIFICE",
            "result": "投手前犧牲短打 (1出局)",
            "description": f"【第 8 棒】{guest_name} 8 棒：點出投手前滾地球護送跑者上二壘得點圈，打者一壘前出局【第 1 出局】！(1 出局二壘有人)",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{guest_name} 8 棒",
            "batter_pos": "RF",
            "batter_num": "5",
            "rbi": 0,
        },
        {
            "id": "pa_top3_3",
            "order_label": "第 9 棒 (二巡)",
            "timestamp_sec": 2965.0, # 49:25
            "inning_num": 3,
            "inning_half": "TOP",
            "event_type": "SINGLE",
            "result": "中外野適時安打 (得分)",
            "description": f"🔥【第 9 棒】{guest_name} 9 棒：擊出中外野穿越安打！二壘跑者奔回本壘得分！(比分 {guest_name} 9 : 1 {home_name})",
            "runs_scored": 1,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 9 棒",
            "batter_pos": "2B",
            "batter_num": "4",
            "rbi": 1,
        },
        {
            "id": "pa_top3_4",
            "order_label": "第 1 棒 (三巡)",
            "timestamp_sec": 3040.0, # 50:40
            "inning_num": 3,
            "inning_half": "TOP",
            "event_type": "DOUBLE",
            "result": "右外野二壘安打 (得分)",
            "description": f"🔥【第 1 棒】{guest_name} 1 棒：再補上一記右外野深遠二壘安打！送回一壘跑者再添 1 分！(比分 {guest_name} 10 : 1 {home_name}, 1 出局二壘有人)",
            "runs_scored": 1,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 1 棒",
            "batter_pos": "CF",
            "batter_num": "7",
            "rbi": 1,
        },
        {
            "id": "pa_top3_5",
            "order_label": "第 2 棒 (三巡)",
            "timestamp_sec": 3110.0, # 51:50
            "inning_num": 3,
            "inning_half": "TOP",
            "event_type": "GROUNDOUT",
            "result": "三壘滾地刺殺 (2出局)",
            "description": f"【第 2 棒】{guest_name} 2 棒：擊出三壘強襲球傳一壘刺殺出局【第 2 出局】！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{guest_name} 2 棒",
            "batter_pos": "SS",
            "batter_num": "6",
            "rbi": 0,
        },
        {
            "id": "pa_top3_6",
            "order_label": "第 3 棒 (三巡)",
            "timestamp_sec": 3190.0, # 53:10
            "inning_num": 3,
            "inning_half": "TOP",
            "event_type": "INNING_SWITCH",
            "result": "投手滾地刺殺 (3出局換局)",
            "description": f"【第 3 棒】{guest_name} 3 棒：擊成投手正面滾地球傳一壘出局！【第 3 出局 ‧ 攻守交換】，{guest_name} 本局追加 2 分，比分來到 10 : 1！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{guest_name} 3 棒",
            "batter_pos": "P",
            "batter_num": "1",
            "rbi": 0,
        }
    ]

    # ================== 第 3 局下半 (0 分) ==================
    bottom_3_events = [
        {
            "id": "pa_bot3_1",
            "order_label": "第 1 棒 (二巡)",
            "timestamp_sec": 3320.0, # 55:20
            "inning_num": 3,
            "inning_half": "BOTTOM",
            "event_type": "SINGLE",
            "result": "中間平飛安打",
            "description": f"【第 1 棒】{home_name} 1 棒：首名打者敲出中外野強勁落地安打站上一壘！(0 出局一壘有人)",
            "runs_scored": 0,
            "outs_recorded": 0,
            "batter_name": f"{home_name} 1 棒",
            "batter_pos": "SS",
            "batter_num": "10",
            "rbi": 0,
        },
        {
            "id": "pa_bot3_2",
            "order_label": "第 2 棒 (二巡)",
            "timestamp_sec": 3390.0, # 56:30
            "inning_num": 3,
            "inning_half": "BOTTOM",
            "event_type": "FLYOUT",
            "result": "中外野飛球接殺 (1出局)",
            "description": f"【第 2 棒】{home_name} 2 棒：擊出中外野高飛球遭到鎖定接殺【第 1 出局】！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{home_name} 2 棒",
            "batter_pos": "P",
            "batter_num": "1",
            "rbi": 0,
        },
        {
            "id": "pa_bot3_3",
            "order_label": "第 3 棒 (二巡)",
            "timestamp_sec": 3465.0, # 57:45
            "inning_num": 3,
            "inning_half": "BOTTOM",
            "event_type": "STRIKEOUT",
            "result": "揮棒落空三振 (2出局)",
            "description": f"【第 3 棒】{home_name} 3 棒：打者揮棒落空遭到三振出局【第 2 出局】！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{home_name} 3 棒",
            "batter_pos": "3B",
            "batter_num": "6",
            "rbi": 0,
        },
        {
            "id": "pa_bot3_4",
            "order_label": "第 4 棒 (二巡)",
            "timestamp_sec": 3540.0, # 59:00
            "inning_num": 3,
            "inning_half": "BOTTOM",
            "event_type": "INNING_SWITCH",
            "result": "游擊滾地刺殺 (3出局換局)",
            "description": f"【第 4 棒】{home_name} 4 棒：擊出內野滾地球傳一壘封殺！【第 3 出局 ‧ 攻守交換】，{home_name} 留下殘壘未能得分，3 局結束 {guest_name} 10 : 1 {home_name}！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{home_name} 4 棒",
            "batter_pos": "1B",
            "batter_num": "5",
            "rbi": 0,
        }
    ]

    # ================== 第 4 局上半 (0 分) ==================
    top_4_events = [
        {
            "id": "pa_top4_1",
            "order_label": "第 4 棒 (三巡)",
            "timestamp_sec": 3690.0, # 61:30
            "inning_num": 4,
            "inning_half": "TOP",
            "event_type": "GROUNDOUT",
            "result": "三壘滾地刺殺 (1出局)",
            "description": f"【第 4 棒】{guest_name} 4 棒：擊出三壘滾地球遭刺殺出局【第 1 出局】！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{guest_name} 4 棒",
            "batter_pos": "3B",
            "batter_num": "10",
            "rbi": 0,
        },
        {
            "id": "pa_top4_2",
            "order_label": "第 5 棒 (三巡)",
            "timestamp_sec": 3755.0, # 62:35
            "inning_num": 4,
            "inning_half": "TOP",
            "event_type": "WALK",
            "result": "四壞球保送",
            "description": f"【第 5 棒】{guest_name} 5 棒：選到四壞球保送站上一壘 (1 出局一壘有人)",
            "runs_scored": 0,
            "outs_recorded": 0,
            "batter_name": f"{guest_name} 5 棒",
            "batter_pos": "1B",
            "batter_num": "3",
            "rbi": 0,
        },
        {
            "id": "pa_top4_3",
            "order_label": "第 6 棒 (三巡)",
            "timestamp_sec": 3820.0, # 63:40
            "inning_num": 4,
            "inning_half": "TOP",
            "event_type": "FLYOUT",
            "result": "右外野飛球接殺 (2出局)",
            "description": f"【第 6 棒】{guest_name} 6 棒：擊出右外野高飛球遭接殺出局【第 2 出局】！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{guest_name} 6 棒",
            "batter_pos": "C",
            "batter_num": "2",
            "rbi": 0,
        },
        {
            "id": "pa_top4_4",
            "order_label": "第 7 棒 (三巡)",
            "timestamp_sec": 3890.0, # 64:50
            "inning_num": 4,
            "inning_half": "TOP",
            "event_type": "INNING_SWITCH",
            "result": "游擊平飛球接殺 (3出局換局)",
            "description": f"【第 7 棒】{guest_name} 7 棒：強勁平飛球直接進游擊手手套！【第 3 出局 ‧ 攻守交換】，{home_name} 守備發揮穩守 4 上無失分！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{guest_name} 7 棒",
            "batter_pos": "LF",
            "batter_num": "8",
            "rbi": 0,
        }
    ]

    # ================== 第 4 局下半 (0 分 ‧ 比賽裁定結束) ==================
    bottom_4_events = [
        {
            "id": "pa_bot4_1",
            "order_label": "第 5 棒 (二巡)",
            "timestamp_sec": 4030.0, # 67:10
            "inning_num": 4,
            "inning_half": "BOTTOM",
            "event_type": "WALK",
            "result": "四壞球保送",
            "description": f"【第 5 棒】{home_name} 5 棒：四壞保送上一壘 (0 出局一壘有人)",
            "runs_scored": 0,
            "outs_recorded": 0,
            "batter_name": f"{home_name} 5 棒",
            "batter_pos": "CF",
            "batter_num": "11",
            "rbi": 0,
        },
        {
            "id": "pa_bot4_2",
            "order_label": "第 6 棒 (二巡)",
            "timestamp_sec": 4100.0, # 68:20
            "inning_num": 4,
            "inning_half": "BOTTOM",
            "event_type": "STRIKEOUT",
            "result": "揮棒落空三振 (1出局)",
            "description": f"【第 6 棒】{home_name} 6 棒：{guest_name} 投手投出好球揮空三振【第 1 出局】！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{home_name} 6 棒",
            "batter_pos": "C",
            "batter_num": "2",
            "rbi": 0,
        },
        {
            "id": "pa_bot4_3",
            "order_label": "第 7 棒 (二巡)",
            "timestamp_sec": 4170.0, # 69:30
            "inning_num": 4,
            "inning_half": "BOTTOM",
            "event_type": "FLYOUT",
            "result": "內野高飛接殺 (2出局)",
            "description": f"【第 7 棒】{home_name} 7 棒：擊出一壘後方小飛球遭一壘手穩穩鎖定接殺【第 2 出局】！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{home_name} 7 棒",
            "batter_pos": "LF",
            "batter_num": "8",
            "rbi": 0,
        },
        {
            "id": "pa_bot4_4",
            "order_label": "第 8 棒 (二巡)",
            "timestamp_sec": 4240.0, # 70:40
            "inning_num": 4,
            "inning_half": "BOTTOM",
            "event_type": "GAME_OVER",
            "result": "內野滾地刺殺 (3出局 ‧ 比賽結束)",
            "description": f"🏆【第 8 棒】{home_name} 8 棒：擊出三壘滾地球，三壘手穩健傳向一壘完成刺殺！【第 3 出局 ‧ 全場比賽結束】！因達少棒 4 局 9 分差大會裁定提前結束比賽規定，終場 {guest_name} 以 10 : 1 大勝 {home_name}，奪得勝利！",
            "runs_scored": 0,
            "outs_recorded": 1,
            "batter_name": f"{home_name} 8 棒",
            "batter_pos": "RF",
            "batter_num": "7",
            "rbi": 0,
        }
    ]

    # 全場 8 個半局列表
    all_innings = [
        {
            "inning_num": 1,
            "inning_half": "TOP",
            "guest_runs": 8,
            "home_runs": 0,
            "summary_text": f"【第 1 局上半攻守記錄】{guest_name} 單局進攻 12 打席，首棒安打盜壘、次棒場內全壘打先馳得點，隨後選保送與適時安打串聯狂灌 8 分；{home_name} 守備於 14:38 (1出局)、17:57 (2出局) 與 21:47 (3出局) 成功換局！",
            "events": top_1_events,
        },
        {
            "inning_num": 1,
            "inning_half": "BOTTOM",
            "guest_runs": 0,
            "home_runs": 1,
            "summary_text": f"【第 1 局下半攻守記錄】{home_name} 展開反攻！首棒滾地出局後，第 2 棒敲出驚天動地的中外野深遠「場內全壘打」打破鴨蛋奪下 1 分！隨後第 4 棒敲安、第 5 棒選到保送攻佔一二壘得點圈，{guest_name} 於 36:15 抓下第 3 個出局數，1 局結束比分 {guest_name} 8 : 1 {home_name}！",
            "events": bottom_1_events,
        },
        {
            "inning_num": 2,
            "inning_half": "TOP",
            "guest_runs": 0,
            "home_runs": 0,
            "summary_text": f"【第 2 局上半攻守記錄】{guest_name} 首棒敲安上壘，但 {home_name} 游擊與二壘防線隨即發動行雲流水的 6-4-3 雙殺守備阻斷攻勢，順利守下半局無失分，比分維持 8 : 1！",
            "events": top_2_events,
        },
        {
            "inning_num": 2,
            "inning_half": "BOTTOM",
            "guest_runs": 0,
            "home_runs": 0,
            "summary_text": f"【第 2 局下半攻守記錄】{guest_name} 投手展現壓制力，連續送出 2 次三振與 1 次滾地刺殺，乾淨俐落演出三上三下半局！",
            "events": bottom_2_events,
        },
        {
            "inning_num": 3,
            "inning_half": "TOP",
            "guest_runs": 2,
            "home_runs": 0,
            "summary_text": f"【第 3 局上半攻守記錄】{guest_name} 攻勢再起！第 7 棒安打加短打推進，第 9 棒與第 1 棒接連敲出適時長打與二壘安打追加 2 分，比分擴大至 10 : 1！",
            "events": top_3_events,
        },
        {
            "inning_num": 3,
            "inning_half": "BOTTOM",
            "guest_runs": 0,
            "home_runs": 0,
            "summary_text": f"【第 3 局下半攻守記錄】{home_name} 首名打者敲出安打站上一壘，但後續打者擊出飛球與三振遭封殺，留下殘壘無功而返，比分 10 : 1！",
            "events": bottom_3_events,
        },
        {
            "inning_num": 4,
            "inning_half": "TOP",
            "guest_runs": 0,
            "home_runs": 0,
            "summary_text": f"【第 4 局上半攻守記錄】{home_name} 守備頂住壓力，投出 1 次保送後抓下平飛球出局，成功瓦解 {guest_name} 攻勢無失分！",
            "events": top_4_events,
        },
        {
            "inning_num": 4,
            "inning_half": "BOTTOM",
            "guest_runs": 0,
            "home_runs": 0,
            "summary_text": f"【第 4 局下半攻守記錄 ‧ 終場裁定】{home_name} 展開最後反撲，雖首棒選到保送，但 {guest_name} 投手接連抓下三振與最後內野滾地刺殺！四局結束達到少棒提前結束規定，全場比賽正式結束！",
            "events": bottom_4_events,
        }
    ]

    # 全場 4 局攻守記錄表 (Box Score)
    guest_box_score = [
        {"order": 1, "number": "7", "name": f"{guest_name} 1 棒", "pos": "CF", "pa": 4, "ab": 4, "h": 3, "r": 2, "rbi": 1, "bb": 0, "so": 0, "avg": ".750"},
        {"order": 2, "number": "6", "name": f"{guest_name} 2 棒", "pos": "SS", "pa": 4, "ab": 4, "h": 2, "r": 2, "rbi": 4, "bb": 0, "so": 0, "avg": ".500"},
        {"order": 3, "number": "1", "name": f"{guest_name} 3 棒", "pos": "P", "pa": 4, "ab": 3, "h": 0, "r": 1, "rbi": 0, "bb": 1, "so": 0, "avg": ".000"},
        {"order": 4, "number": "10", "name": f"{guest_name} 4 棒", "pos": "3B", "pa": 3, "ab": 3, "h": 2, "r": 1, "rbi": 0, "bb": 0, "so": 0, "avg": ".667"},
        {"order": 5, "number": "3", "name": f"{guest_name} 5 棒", "pos": "1B", "pa": 3, "ab": 2, "h": 1, "r": 1, "rbi": 1, "bb": 1, "so": 0, "avg": ".500"},
        {"order": 6, "number": "2", "name": f"{guest_name} 6 棒", "pos": "C", "pa": 3, "ab": 2, "h": 0, "r": 1, "rbi": 0, "bb": 1, "so": 0, "avg": ".000"},
        {"order": 7, "number": "8", "name": f"{guest_name} 7 棒", "pos": "LF", "pa": 3, "ab": 3, "h": 2, "r": 1, "rbi": 2, "bb": 0, "so": 0, "avg": ".667"},
        {"order": 8, "number": "5", "name": f"{guest_name} 8 棒", "pos": "RF", "pa": 3, "ab": 2, "h": 0, "r": 0, "rbi": 0, "bb": 0, "so": 1, "avg": ".000"},
        {"order": 9, "number": "4", "name": f"{guest_name} 9 棒", "pos": "2B", "pa": 2, "ab": 2, "h": 2, "r": 1, "rbi": 2, "bb": 0, "so": 0, "avg": "1.000"},
    ]

    home_box_score = [
        {"order": 1, "number": "10", "name": f"{home_name} 1 棒", "pos": "SS", "pa": 2, "ab": 2, "h": 1, "r": 0, "rbi": 0, "bb": 0, "so": 0, "avg": ".500"},
        {"order": 2, "number": "1", "name": f"{home_name} 2 棒", "pos": "P", "pa": 2, "ab": 2, "h": 1, "r": 1, "rbi": 1, "bb": 0, "so": 0, "avg": ".500"},
        {"order": 3, "number": "6", "name": f"{home_name} 3 棒", "pos": "3B", "pa": 2, "ab": 2, "h": 0, "r": 0, "rbi": 0, "bb": 0, "so": 1, "avg": ".000"},
        {"order": 4, "number": "5", "name": f"{home_name} 4 棒", "pos": "1B", "pa": 2, "ab": 2, "h": 1, "r": 0, "rbi": 0, "bb": 0, "so": 0, "avg": ".500"},
        {"order": 5, "number": "11", "name": f"{home_name} 5 棒", "pos": "CF", "pa": 2, "ab": 0, "h": 0, "r": 0, "rbi": 0, "bb": 2, "so": 0, "avg": ".000"},
        {"order": 6, "number": "2", "name": f"{home_name} 6 棒", "pos": "C", "pa": 2, "ab": 2, "h": 0, "r": 0, "rbi": 0, "bb": 0, "so": 1, "avg": ".000"},
        {"order": 7, "number": "8", "name": f"{home_name} 7 棒", "pos": "LF", "pa": 2, "ab": 2, "h": 0, "r": 0, "rbi": 0, "bb": 0, "so": 1, "avg": ".000"},
        {"order": 8, "number": "7", "name": f"{home_name} 8 棒", "pos": "RF", "pa": 2, "ab": 2, "h": 0, "r": 0, "rbi": 0, "bb": 0, "so": 0, "avg": ".000"},
        {"order": 9, "number": "4", "name": f"{home_name} 9 棒", "pos": "2B", "pa": 1, "ab": 1, "h": 0, "r": 0, "rbi": 0, "bb": 0, "so": 1, "avg": ".000"},
    ]

    # 局數得分線表 (Line Score) - 4 局裁定
    line_score = {
        "innings": ["1", "2", "3", "4", "5", "6"],
        "guest": {"name": guest_name, "scores": ["8", "0", "2", "0", "X", "X"], "r": 10, "h": 12, "e": 0},
        "home": {"name": home_name, "scores": ["1", "0", "0", "0", "X", "X"], "r": 1, "h": 3, "e": 2}
    }

    return {
        "guest_name": guest_name,
        "home_name": home_name,
        "guest_score": 10,
        "home_score": 1,
        "line_score": line_score,
        "guest_box_score": guest_box_score,
        "home_box_score": home_box_score,
        "innings": all_innings,
    }
